In [28]:
import pandas as pd
headers_path = r'C:\Users\GLVC5389\Desktop\Master_DF-IA\Data Process\Mini_projet\header.csv'
data_path = r'C:\Users\GLVC5389\Desktop\Master_DF-IA\Data Process\Mini_projet\BF.csv'


#lecture des entêtes

with open(headers_path, 'r') as file:
    headers = file.readline().split(';')
 
    #Lecture des données

data = pd.read_csv(data_path, header=None, sep=';')

#Recupération des entêtes
data.columns = headers

# traitement des espaces
data.columns = data.columns.str.replace(r"^\s+|\s+$", "", regex=True)

print(data.columns)

Index(['geonameid', 'name', 'asciiname', 'alternatenames', 'latitude',
       'longitude', 'classe de fonctionnalités', 'code de fonctionnalité',
       'code pays', 'cc2', 'code admin1', 'code admin2', 'code admin3',
       'code admin4', 'population', 'altitude', 'dem', 'timezone',
       'date de modification'],
      dtype='object')

In [30]:
new_comlumns = ['geonameid', 'name', 'latitude', 'longitude']

new_data = data[new_comlumns]

new_columns = {'geonameid': 'ID', 'name': 'location_name', 'latitude': 'latitudes', 'longitude': 'longitudes'}

new_data_renamed = new_data.rename(columns=new_columns)

new_data_renamed

             ID       location_name  latitudes  longitudes
0       2282318              Pouéné    9.72908    -2.78660
1       2285251  Léraba Occidentale   10.28333    -5.11667
2       2287216           Kéléouoro    9.80748    -4.05023
3       2294066         White Volta    8.70194    -0.99056
4       2298457        Issana Bouga   10.91667    -1.18333
...         ...                 ...        ...         ...
11708  12688712          Kanliyinou   12.15503     0.59881
11709  12688713     Tinonguen-Peulh   11.64924    -0.22063
11710  12689306            Wolidouo    9.73471    -3.07244
11711  12720016               Yimdi   12.31014    -1.66322
11712  12746364              Dabogo   11.49058     0.12698

[11713 rows x 4 columns]

In [33]:
#Enregistrement du csv
new_data_renamed.to_csv(r'C:\Users\GLVC5389\Desktop\Master_DF-IA\Data Process\Mini_projet\burkina_location.csv', index=False)

In [41]:
#Lignes contenant gounghin

data1 = pd.read_csv(r'C:\Users\GLVC5389\Desktop\Master_DF-IA\Data Process\Mini_projet\burkina_location.csv', sep=',')

df = data1.apply(lambda row: row.astype(str).str.contains('gounghin' ,case=False).any(), axis=1)
df = data1[df]

df

             ID                  location_name  latitudes  longitudes
153     2353306                       Gounghin   12.06677    -1.42134
7270    2360473                       Gounghin   12.62488    -1.36398
10259   2570204                       Gounghin   12.31436    -1.37900
10745  10342749                       Gounghin   12.06667    -0.15000
10758  10629032             BICIAB // Gounghin   12.35921    -1.54273
10817  11257296            Gounghin Department   12.06671    -0.15484
10844  11900526                  Gounghin Nord   12.36120    -1.55055
10845  11900528  Zone Industrielle de Gounghin   12.36631    -1.54137
10851  11900619                   Gounghin Sud   12.35298    -1.54342
10865  11900680                       Gounghin   12.35895    -1.54442

In [42]:
#Enregistrement dans un csv
df.to_csv(r'C:\Users\GLVC5389\Desktop\Master_DF-IA\Data Process\Mini_projet\gounghin.csv', index=False)

In [46]:
#Recuperation des lignes sur le DF burkina_location.csv dont les noms commencent par A...P

df = new_data_renamed[new_data_renamed['location_name'].str.upper().str[0].between('A', 'P')]

df = df.sort_values(by='location_name')

df

             ID location_name  latitudes  longitudes
10647   6913771        Abanda   15.06808    -0.59805
10032   2363251        Abanga   13.32429     0.31151
11092  11980339        Abassi   12.27728    -1.13662
10600   6874881         Abaye   13.44080    -3.90190
10030   2363249          Abra   13.09140    -1.34752
...         ...           ...        ...         ...
10110   2570015       Pézinga   12.05298    -1.47002
3479    2356655            Pê   11.30000    -3.53333
3280    2356454            Pô   11.16972    -1.14500
3279    2356453            Pô   12.30000    -2.61667
10393   6296406    Pô Airport   11.17854    -1.14498

[8131 rows x 4 columns]

In [50]:
#Enregistrement dans un csv
df.to_csv(r'C:\Users\GLVC5389\Desktop\Master_DF-IA\Data Process\Mini_projet\A_to_P.csv', index=False)

In [48]:
# Trouver les latitudes et longitudes minimales et afficher les noms correspondant

#Recupérer les index min

index_latitude_min = new_data_renamed['latitudes'].idxmin()
index_longitude_min = new_data_renamed['longitudes'].idxmin()

# Recuperer les valeurs min

latitude_min = new_data_renamed.loc[index_latitude_min, 'latitudes']
longitude_min = new_data_renamed.loc[index_longitude_min, 'longitudes']

# Recuperer les noms

nom_latitude_min = new_data_renamed.loc[index_latitude_min, 'location_name']
nom_longitude_min = new_data_renamed.loc[index_longitude_min, 'location_name']

# Afficher les résultats
print(f"Latitude minimale: {latitude_min}, Lieu: {nom_latitude_min}")
print(f"Longitude minimale: {longitude_min}, Lieu: {nom_longitude_min}")

Latitude minimale: 5.21609, Lieu: Komoé
Longitude minimale: -5.65968, Lieu: Banifing

In [49]:
# les lieux dont les coordonnées sont comprises entre (lat >= 11 et lon <= 0.5)

lieux = new_data_renamed[(new_data_renamed['latitudes'] >= 11) & (new_data_renamed['longitudes'] <= 0.5)]

lieux

             ID    location_name  latitudes  longitudes
5       2353158         Zyonguen   12.36667    -0.45000
6       2353159        Zyiliwèlè   12.38333    -2.73333
7       2353160           Zyanko   12.78333    -0.41667
8       2353161            Zouta   13.14908    -1.28197
9       2353162        Zourtenga   12.95741    -1.28745
...         ...              ...        ...         ...
11706  12687046         Monde-So   14.20081    -1.63983
11707  12688694          Yerfing   11.33747    -3.35025
11709  12688713  Tinonguen-Peulh   11.64924    -0.22063
11711  12720016            Yimdi   12.31014    -1.66322
11712  12746364           Dabogo   11.49058     0.12698

[9282 rows x 4 columns]